/// Flutter icons BottomNavigation
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BottomNavigation
///      fonts:
///       - asset: fonts/BottomNavigation.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class BottomNavigation {
  BottomNavigation._();

  static const _kFontFam = 'BottomNavigation';
  static const String? _kFontPkg = null;

  static const IconData home = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData activity = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
