// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8R0_M8LizywlVSM9ti5BVYf5qLw7QwZ4',
    appId: '1:5961971449:web:ca181604c14e038a7c5428',
    messagingSenderId: '5961971449',
    projectId: 'fitnestx-f88c2',
    authDomain: 'fitnestx-f88c2.firebaseapp.com',
    storageBucket: 'fitnestx-f88c2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_t4eYV3qG2lyo1est1_YqxLLtE3Quaqs',
    appId: '1:5961971449:android:2a97fb4cbebfdaf97c5428',
    messagingSenderId: '5961971449',
    projectId: 'fitnestx-f88c2',
    storageBucket: 'fitnestx-f88c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeOeu1iNnt6n4kgEsWiHB3vMpB-0E-1dU',
    appId: '1:5961971449:ios:69cf24c581a10ecd7c5428',
    messagingSenderId: '5961971449',
    projectId: 'fitnestx-f88c2',
    storageBucket: 'fitnestx-f88c2.appspot.com',
    iosBundleId: 'com.fitnesxflutter.fitnesxFlutter',
  );

}