/// Flutter icons Fitnestx
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Fitnestx
///      fonts:
///       - asset: fonts/Fitnestx.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Fitnestx {
  Fitnestx._();

  static const _kFontFam = 'Fitnestx';
  static const String? _kFontPkg = null;

  static const IconData user_2 = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
