/// Flutter icons ProfileScreenIcon
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ProfileScreenIcon
///      fonts:
///       - asset: fonts/ProfileScreenIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ProfileScreenIcon {
  ProfileScreenIcon._();

  static const _kFontFam = 'ProfileScreenIcon';
  static const String? _kFontPkg = null;

  static const IconData chart = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData document = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData graph = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData setting = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shield_done = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
